server:
  servlet:
    context-path: /manage
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/new_api?characterEncoding=utf-8&useSSL=false
    username: root
    password: 931208
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    show-sql: true
apiLength: 8


